# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RLCoreAnimationPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SQLite.swift'
  pod 'SwiftyBeaver'
  
  pod 'SnapKit'

  # Pods for RLCoreAnimationPractice

  target 'RLCoreAnimationPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RLCoreAnimationPracticeUITests' do
    # Pods for testing
  end

end


